#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JSDB_test")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDataTable(DataTable instance);
    partial void UpdateDataTable(DataTable instance);
    partial void DeleteDataTable(DataTable instance);
    partial void Insertlicznik(licznik instance);
    partial void Updatelicznik(licznik instance);
    partial void Deletelicznik(licznik instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["JSDB_testConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DataTable> DataTable
		{
			get
			{
				return this.GetTable<DataTable>();
			}
		}
		
		public System.Data.Linq.Table<licznik> licznik
		{
			get
			{
				return this.GetTable<licznik>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DataTable")]
	public partial class DataTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _nazwa;
		
		private string _dataa;
		
		private string _godzina;
		
		private System.Nullable<int> _usr;
		
		private System.Nullable<int> _roz;
		
		private System.Nullable<int> _pol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    partial void OndataaChanging(string value);
    partial void OndataaChanged();
    partial void OngodzinaChanging(string value);
    partial void OngodzinaChanged();
    partial void OnusrChanging(System.Nullable<int> value);
    partial void OnusrChanged();
    partial void OnrozChanging(System.Nullable<int> value);
    partial void OnrozChanged();
    partial void OnpolChanging(System.Nullable<int> value);
    partial void OnpolChanged();
    #endregion
		
		public DataTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(50)")]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataa", DbType="VarChar(15)")]
		public string dataa
		{
			get
			{
				return this._dataa;
			}
			set
			{
				if ((this._dataa != value))
				{
					this.OndataaChanging(value);
					this.SendPropertyChanging();
					this._dataa = value;
					this.SendPropertyChanged("dataa");
					this.OndataaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_godzina", DbType="VarChar(15)")]
		public string godzina
		{
			get
			{
				return this._godzina;
			}
			set
			{
				if ((this._godzina != value))
				{
					this.OngodzinaChanging(value);
					this.SendPropertyChanging();
					this._godzina = value;
					this.SendPropertyChanged("godzina");
					this.OngodzinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr", DbType="Int")]
		public System.Nullable<int> usr
		{
			get
			{
				return this._usr;
			}
			set
			{
				if ((this._usr != value))
				{
					this.OnusrChanging(value);
					this.SendPropertyChanging();
					this._usr = value;
					this.SendPropertyChanged("usr");
					this.OnusrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roz", DbType="Int")]
		public System.Nullable<int> roz
		{
			get
			{
				return this._roz;
			}
			set
			{
				if ((this._roz != value))
				{
					this.OnrozChanging(value);
					this.SendPropertyChanging();
					this._roz = value;
					this.SendPropertyChanged("roz");
					this.OnrozChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pol", DbType="Int")]
		public System.Nullable<int> pol
		{
			get
			{
				return this._pol;
			}
			set
			{
				if ((this._pol != value))
				{
					this.OnpolChanging(value);
					this.SendPropertyChanging();
					this._pol = value;
					this.SendPropertyChanged("pol");
					this.OnpolChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.licznik")]
	public partial class licznik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _liczbaUsr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnliczbaUsrChanging(System.Nullable<int> value);
    partial void OnliczbaUsrChanged();
    #endregion
		
		public licznik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_liczbaUsr", DbType="Int")]
		public System.Nullable<int> liczbaUsr
		{
			get
			{
				return this._liczbaUsr;
			}
			set
			{
				if ((this._liczbaUsr != value))
				{
					this.OnliczbaUsrChanging(value);
					this.SendPropertyChanging();
					this._liczbaUsr = value;
					this.SendPropertyChanged("liczbaUsr");
					this.OnliczbaUsrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
